name: iOS Unit & UI Tests

on:
  pull_request:
    branches: [ main ]  # adjust as needed
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to avoid .pbxproj corruption

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Find available iOS Simulator
        id: find-sim
        run: |
          SIMULATOR=$(xcrun simctl list devices available | grep -E 'iPhone.*(Booted|Shutdown)' | grep -v unavailable | head -n1 | sed -E 's/^.*([A-F0-9-]{36}).*$/\1/')
          echo "SIMULATOR_ID=$SIMULATOR" >> $GITHUB_ENV

      - name: Boot simulator
        run: xcrun simctl boot "$SIMULATOR_ID" || true

      - name: Build app (Simulator)
        run: |
          xcodebuild \
            -project Clerk.xcodeproj \
            -scheme Clerk \
            -sdk iphonesimulator \
            -destination "id=$SIMULATOR_ID" \
            -configuration Release \
            clean build

      - name: Run Tests
        run: |
          xcodebuild \
            -project Clerk.xcodeproj \
            -scheme Clerk \
            -sdk iphonesimulator \
            -destination "id=$SIMULATOR_ID" \
            -configuration Release \
            test
