name: iOS Unit & UI Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test: # Renamed job for clarity
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history to avoid .pbxproj corruption

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest' # It's good practice to be explicit, e.g., '16.0'

      - name: Run tests
        run: |
          # Find a valid, available iOS Simulator destination from xcodebuild's perspective
          # This is more reliable than parsing 'xcrun simctl list'
          DESTINATION=$(xcodebuild -showdestinations -project Clerk.xcodeproj -scheme Clerk | grep "platform:iOS Simulator" | head -n 1)
          
          echo "Found destination: $DESTINATION"

          xcodebuild \
            -project Clerk.xcodeproj \
            -scheme Clerk \
            -destination "$DESTINATION" \
            -sdk iphonesimulator \
            -configuration Release \
            clean test
