name: iOS Unit & UI Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest'

      # Reads content from the SECRETS_PLIST_CONTENT secret in repo settings
      - name: Create Secrets.plist
        env:
          SECRETS_CONTENT: ${{ secrets.SECRETS_PLIST_CONTENT }}
        run: |
          echo "Creating Secrets.plist..."
          echo "$SECRETS_CONTENT" > Clerk/Clerk/Secrets.plist
          echo "Secrets.plist created successfully."
      
      - name: Run tests on a standard simulator
        run: |
          # Directly specify a standard simulator. This is often more reliable in CI.
          # Using 'OS=latest' allows Xcode to pick the correct OS version automatically.
          xcodebuild \
            -project Clerk.xcodeproj \
            -scheme Clerk \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest' \
            -sdk iphonesimulator \
            -configuration Release \
            clean test
