name: iOS Unit & UI Tests

on:
  pull_request:
    branches: [ main ]  # adjust as needed
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to avoid .pbxproj corruption

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Build app
        run: |
          xcodebuild \
            -project Clerk.xcodeproj \
            -scheme Clerk \
            -sdk iphoneos \
            -configuration Release \
            clean build
